### ISSUE TITLE
Oxygen Debye Waller factor

### ISSUE THREAD

**Issue by HamishGBrown** [stevenspurgeon/xtl-converter#1]
Hi Steve,

Hamish Brown from the Monash school of physics here, I'm currently maintaining the MuSTEM multislice code. Thanks for making available such a helpful resource for MuSTEM users. I have just one question: the oxygen Debye-Waller factor given is 0.9275, the one for oxygen in the example SrTiO3 is 0.009275, is this a simple transcription error?

Thanks in Advance,
Hamish

**Comment by stevenspurgeon** [comment]
Hi Hamish,

Thanks so much for catching this typo. You are correct that the DWF is actually 0.009275. I will correct this ASAP and release a new version.
